// Static reference data used by the UI. Admin-managed content lives in Firestore;
// these are not seeded into the database — they are fallbacks/option lists only.

export const regions = ['NCR', 'CAR', 'Visayas', 'Mindanao', 'Luzon'];

// Presbytery shape:
// {
//   id, name, region, description, seat?, website?,
//   officers: [{ name, role, contact?, email?, photo? }],
//   churches: [{ name, address, minister, associatePastors?, contact?, email?, worshipTime?, elders?: [name] }]
// }
export const defaultPresbyteries = [
    { id: '1', name: 'Northern Luzon Presbytery', region: 'Luzon', officers: [], churches: [], description: 'Regional council overseeing Presbyterian churches in Northern Luzon.' },
    { id: '2', name: 'Central Luzon North Presbytery', region: 'Luzon', officers: [], churches: [], description: 'Serving the Northern parts of Central Luzon.' },
    { id: '3', name: 'Central Luzon Presbytery', region: 'Luzon', officers: [], churches: [], description: 'The main regional council for Central Luzon.' },
    {
        id: '4',
        name: 'Western Luzon Presbytery',
        region: 'Luzon',
        description: 'Overseeing churches across Western Luzon.',
        officers: [
            { name: 'Rev. Norman Bayogos', role: 'Moderator' },
            { name: 'Rev. Enrique Abad Jr.', role: 'Vice-Moderator' },
            { name: 'Rev. Joemari Sabocojan', role: 'Secretary' },
            { name: 'Rev. Arnulfo Baylon', role: 'Treasurer' },
        ],
        churches: [
            {
                name: 'Mariveles Presbyterian Church (MPC)',
                address: 'Prk. 1 Brgy. Ipag, Mariveles, Bataan',
                minister: 'Rev. Norman Bayogos',
                associatePastors: ['Ptr. Ricky Mater', 'Ptr. Fernando Araga'],
                contact: '09959202174',
                worshipTime: '10:00 AM – 12:00 NN',
                elders: ['Elder Michael Jagonob', 'Elder Carlito Gacayan'],
            },
            {
                name: 'Linasin Presbyterian Church (LPC)',
                address: 'Prk. 2 Brgy. Linasin, San Marcelino, Zambales',
                minister: 'Rev. Arnulfo Baylon',
                worshipTime: '9:00 AM – 11:00 AM',
                elders: ['Elder Edwin Lubong', 'Elder Fernando Manansala'],
            },
            {
                name: 'Subic Pag-asa Christian Church (SPCC)',
                address: 'Evangelista St., Pamatawan, Subic, Zambales',
                minister: 'Rev. Erowin Gongora',
                contact: '09812210749',
                worshipTime: '10:00 AM – 12:00 NN',
                elders: ['Elder Ambrosio Agan Jr.', 'Elder Buenaventura Francisco Jr.'],
            },
            {
                name: 'Pag-asa Presbyterian Community Church (PPCC)',
                address: 'Sitio Lawin, San Rafael, San Marcelino, Zambales',
                minister: 'Rev. Enrique Abad Jr.',
                contact: '09630290703 / 09949282331',
                worshipTime: '9:30 AM – 11:00 AM',
                elders: ['Elder Eric Abad'],
            },
            {
                name: 'Olongapo Pag-asa Christian Church (OPCC)',
                address: 'Prk. 5, Santan St., New Cabalan, Olongapo City, Zambales',
                minister: 'Rev. Joemari P. Sabocojan',
                contact: '09203184529',
                worshipTime: '9:30 AM – 11:30 AM',
            },
            {
                name: 'City on a Hill Mission Church (CMC)',
                address: 'Palanginan, Iba, Zambales',
                associatePastors: ['Ptr. Wilson Balmori'],
                contact: '09279101319 / 09088914077',
                worshipTime: '10:00 AM – 12:00 NN',
            },
            {
                name: 'Presbyterian Joeun Mission Church (PJMC)',
                address: 'Purok 1, Martin Subd., Del Pilar, Castillejos, Zambales',
                associatePastors: ['Ptr. Francis Jeric Callo'],
                contact: '09178860803',
                worshipTime: '11:00 AM – 1:00 PM',
            },
            {
                name: 'Aglao Pag-asa Christian Church (APCC)',
                address: 'Aglao, San Marcelino, Zambales',
                minister: 'Rev. Jesus Binoya',
                worshipTime: '8:00 AM – 10:00 AM',
            },
            {
                name: 'Pag-asa Presbyterian Church (PPC)',
                address: 'Mambog, Botolan, Zambales',
                minister: 'Rev. Jesus Dela Cruz',
                contact: '09165917822',
                worshipTime: '9:30 AM – 11:00 AM',
                elders: ['Elder Roderick Calma'],
            },
            {
                name: 'Kalooban ng Diyos Pagasa Christian Church (KDPCC)',
                address: 'Naugsol, Subic, Zambales',
                minister: 'Rev. Redentor Eclevia',
                contact: '09079476899',
                worshipTime: '9:00 AM – 11:00 AM',
            },
        ],
    },
    {
        id: '5',
        name: 'NCR Presbytery - North Metro',
        region: 'NCR',
        description: 'Serving churches in the Northern Metro Manila area.',
        officers: [],
        churches: [
            {
                name: 'Sungbok Presbyterian Church',
                minister: 'Rev. Virgilio A. Delas Armas',
                contact: '0999 813 3334',
                email: 'gildelasarmas@yahoo.com',
            },
            {
                name: 'Blessed Suan Presbyterian Church',
                minister: 'Pastor Danilo S. Cagape',
                contact: '0969 237 7771',
                email: 'dannycagape1967@gmail.com',
            },
            {
                name: 'Blessed Harvest Christian Church',
                minister: 'Pastor Luvimin P. Zacal',
                contact: '0995 541 0882',
                email: 'luveden.zacal@gmail.com',
            },
            {
                name: 'Pilgrims Presbyterian Church',
                minister: 'Rev. Jester C. Azarcon',
                email: 'thmtheology@gmail.com',
            },
            {
                name: 'Jesus Cares Presbyterian Church',
                minister: 'Rev. Juan M. Manago',
                contact: '0918 555 7550',
                email: 'gospellifechurch@yahoo.com',
            },
            {
                name: 'Liberty Presbyterian Church',
                minister: 'Rev. Rodolfo F. Megano',
                contact: '0977 237 9636',
                email: 'meganorodolfo682@gmail.com',
            },
            {
                name: 'Light of the World Presbyterian Church',
                minister: 'Rev. Nelson M. Dangan',
                associatePastors: ['Rev. Dan De Jesus'],
                contact: '0921 871 3080',
                email: 'nmd_pcp@yahoo.com',
                elders: ['Elder Pablito S. Daradal'],
            },
            {
                name: 'Covenant Presbyterian Church',
                address: '#22 Isidora St., Don Antonio Heights, Brgy. Holy Spirit, Quezon City',
                minister: 'Rev. Roberto G. Fabia',
                contact: '0923 528 1416',
                email: 'robert.fabia@gmail.com',
                elders: ['Elder Ernesto A. Gamayot Jr.'],
            },
            {
                name: 'Maysan Presbyterian Church',
                address: '92 G. Marcelo St., Maysan, Valenzuela City',
                minister: 'Rev. Roger S. Samsona',
                contact: '0915 148 4235',
            },
            {
                name: 'Eunjwa Victory Presbyterian Church',
                minister: 'Rev. Julito H. Venus',
                associatePastors: ['Rev. Rolando Verches'],
                contact: '0916 214 6262',
                email: 'lauven2mission@yahoo.com',
                elders: ['Elder Joel A. Fetalco'],
            },
            {
                name: 'JILLPC (Jesus is the Lord of Life Presbyterian Church)',
                address: '1 West Santiago St., Brgy. Paltok, Quezon City',
                minister: 'Rev. Dr. JungKyu Park',
                contact: '0995 109 4967',
                email: 'kopilyouth513@gmail.com',
            },
            {
                name: 'Montalban Presbyterian Banglim Mission Church',
                minister: 'Rev. Dr. JungKyu Park',
                associatePastors: ['Pastora Leslie D. Cimanes'],
                elders: ['Elder Edilberto V. Asia'],
            },
            {
                name: 'Inchang Shepherds Presbyterian Church',
                minister: 'Rev. Dr. JungKyu Park',
            },
            {
                name: 'ToughGuys-PDM',
                minister: 'Rev. Sheth Villacortes Sali',
                contact: '0948 388 2824',
                email: 'Sheth.Sali@deped.gov.ph',
            },
            {
                name: 'Serving Mission Palosapis Presbyterian Church',
                minister: 'Pastora Nida M. Tecson',
                contact: '0915 003 3165',
                email: 'nidatecson997@gmail.com',
            },
            {
                name: 'San Rafael Banglim Presbyterian Church',
                minister: 'Pastora Josephine A. Adul',
                email: 'amatajosephine@gmail.com',
            },
        ],
    },
    {
        id: '6',
        name: 'Rizal Presbytery',
        region: 'Luzon',
        description: 'Serving the province of Rizal and surrounding areas.',
        officers: [
            { name: 'Rev. Lito Malicdem', role: 'Moderator', contact: '09062206748' },
            { name: 'Rev. Alexander Landeza', role: 'Vice Moderator', contact: '09424015125' },
            { name: 'Rev. Emil E. De Guia', role: 'Recording Clerk', contact: '09389939760' },
            { name: 'Rev. Vhong Rubianes', role: 'Treasurer', contact: '09034302208' },
            { name: 'Rev. Jeffrey Sunga', role: 'Auditor', contact: '09169273601' },
        ],
        churches: [
            {
                name: 'Binangonan Disciple-Making Church',
                address: '253 St. Bernard St., San Valentin, Pantok, Binangonan, Rizal',
                minister: 'Rev. Christian Ylagan',
                contact: '09277207998',
                worshipTime: '10:30 AM',
            },
            {
                name: 'Bright Voice Presbyterian Church',
                address: 'Cantorab St., Bgy. San Roque, Antipolo City, Rizal',
                minister: 'Rev. Joselito Malicdem',
                contact: '09062206748',
                worshipTime: '10:00 AM',
            },
            {
                name: 'Cardona Dae Heung Presbyterian Church',
                address: 'Liwanag St., Sitio Ampucao, Brgy. Iglesia, Cardona, Rizal',
                minister: 'Mr. Arjay Costales',
                contact: '09268702495',
                worshipTime: '10:00 AM',
            },
            {
                name: 'Shinam Full of Grace Presbyterian Church',
                address: 'Purok Sagingan, Bgy. San Isidro, Antipolo City, Rizal',
                minister: 'Rev. Leonardo Angeles',
                contact: '09950170296',
                worshipTime: '10:00 AM',
            },
            {
                name: 'Guinayang Presbyterian Church',
                address: 'Guinayang, San Mateo, Rizal',
                minister: 'Rev. Arturo Dumayag',
                contact: '09773664760',
                worshipTime: '9:00 AM',
            },
            {
                name: 'Jesus Sanctuary Sung Nam Presbyterian Church',
                address: 'Avocado St., Dela Paz, Cogeo, Antipolo City, Rizal',
                minister: 'Rev. Napoleon Capili',
                associatePastors: ['Rev. Vhong Rubianes'],
                contact: '09103818067',
                worshipTime: '10:00 AM – 12:00 NN',
            },
            {
                name: 'Good Shepherd Presbyterian Church',
                address: 'Montalban, Rizal',
                minister: 'Rev. Joselito Malicdem',
                contact: '09062206748',
                worshipTime: '10:00 AM',
            },
            {
                name: 'Jubilee Presbyterian Church',
                address: 'St. Matthew St., Marvi Hills Subd., Brgy. Gulod Malaya, San Mateo, Rizal',
                minister: 'Israel Jacob Dumayag',
                contact: '09655834554',
            },
            {
                name: 'Mt. Zion Presbyterian Church',
                address: 'Blk. 25 Lot 2, Nathalie Ave., Cor. Blue Jasmine St., Antipolo Hills, Antipolo City',
                minister: 'Rev. Salvador Garaña',
                contact: '09455602583',
                worshipTime: '9:30 AM – 11:30 AM',
            },
            {
                name: 'Riverside Presbyterian Church',
                address: 'Road 11, Nagkaisang Nayon St., Nagtinig, Taytay, Rizal',
                minister: 'Rev. Santiago Calvez',
                contact: '09382839927',
                worshipTime: '10:30 AM',
            },
            {
                name: 'Teresa Presbyterian Church',
                address: 'F. Changco St., Dulumbayan, Teresa, Rizal',
                minister: 'Rev. John Paulo M. Solomon',
                contact: '09979181556',
            },
            {
                name: 'Tubig na Nagbibigay Buhay Presbyterian Church',
                address: 'Bautista, San Jose, Antipolo City, Rizal',
                minister: 'Rev. Napoleon Capili',
                associatePastors: ['Pastor Michael Guzman'],
                contact: '09103818067',
                worshipTime: '9:00 AM – 11:00 AM',
            },
            {
                name: 'Tumana Presbyterian Church',
                address: '44 Road 1, Doña Petra, Bgy. Tumana, Marikina City',
                minister: 'Rev. Emil De Guia',
                contact: '09389939760',
                worshipTime: '11:00 AM',
            },
            {
                name: "Good Shepherd's Covenant Reformed Church (GSCRC, Inc.)",
                address: '69-D Manga St., Elmars Subd., Bgy. Cupang, Antipolo City',
                minister: 'Rev. Jose T. Leosala',
                contact: '09205512225',
                worshipTime: '10:00 AM – 12:00 NN',
            },
            {
                name: 'Tower of Faith Presbyterian Church',
                address: '453 C. Sampaguita St., Bgy. Sampaloc, Tanay, Rizal',
                minister: 'Rev. Vicente Asis',
                contact: '09653278011',
                worshipTime: '9:30 AM',
            },
            {
                name: 'Waray Emmanuel Presbyterian Church',
                address: 'Tanay, Rizal',
                minister: 'Rev. Vicente Asis',
                contact: '09653278011',
                worshipTime: '3:00 PM – 5:00 PM',
            },
            {
                name: 'Hisong Christian Fellowship',
                address: '1705 Brookside Dr. Extension, Cainta, 1900 Rizal',
                minister: 'Rev. John Paulo Solomon',
                contact: '09979181556',
            },
            {
                name: 'The Calling Banai Church',
                address: 'Banaiville Multipurpose Hall, San Isidro, Rodriguez, Montalban, Rizal',
                minister: 'Rev. Jeffrey Sunga',
                contact: '09169273601',
                worshipTime: '10:00 AM',
            },
            {
                name: 'Jesus Christ Community Church',
                address: 'Blk. 137, Lot 16, Phase 1, Raja Sumakwel St., Upper Bicutan, Taguig',
                minister: 'Mr. Joemer David S. Tolones',
                contact: '09350422535',
            },
            {
                name: 'Rooted-Faith in Christ Presbyterian Church',
                address: '#627 Gen. Lucban St., Bagong Silangan, Q.C.',
                minister: 'Mr. Francis Porca',
                contact: '09766616479',
                worshipTime: '9:00 AM – 11:00 AM',
            },
        ],
    },
    {
        id: '7',
        name: 'NCR Presbytery - South Metro',
        region: 'NCR',
        description: 'Serving churches in the Southern Metro Manila area.',
        officers: [
            { name: 'Rev. Rodrigo Figueroa', role: 'Moderator' },
            { name: 'Rev. Danilo Tabije', role: 'Vice-Moderator' },
            { name: 'Rev. Menard Diño', role: 'Recording Clerk' },
            { name: 'Elder Leonardo Canto', role: 'Treasurer' },
            { name: "Elder Constancio 'Natan' Cabatay", role: 'Auditor' },
        ],
        churches: [
            {
                name: 'Gospel Mission Presbyterian Church',
                address: '#42 F. Banaag Street, Brgy. Pineda, Pasig City',
                minister: 'Rev. Angelito Carillo',
                contact: '0908-7239093',
                worshipTime: '10:00 AM – 12:00 NN',
                elders: ['Elder Lyndon Calbone', 'Elder Francis Verches', 'Elder Jaime Mahinay'],
            },
            {
                name: 'Ichthus Presbyterian Church',
                address: 'L4 B7, Banner Ave, St. Martin Village, 4th Estate Subd., Brgy. San Antonio, Sucat, Parañaque City',
                minister: 'Rev. Edgar Adra',
                contact: '0935-9955970',
                worshipTime: '10:00 AM – 11:30 AM',
                elders: ['Elder Ferdinand Lorenzana', "Elder Ernesto 'Jhun' Garcia", 'Elder Alexander Co', 'Elder Leonardo Canto'],
            },
            {
                name: 'Grace Community Presbyterian Church',
                address: 'Blk 12 Lot 43 America St., Corner Australia, EP Housing Village, Brgy. Pinagsama Phase 2, Taguig City',
                minister: 'Rev. Rodrigo Figueroa',
                contact: '0945-1196953',
                worshipTime: '10:00 AM – 11:30 AM',
                elders: ['Elder Joel Balabbo', 'Elder Nelson Rodriguez'],
            },
            {
                name: 'Bread for the Word Presbyterian Church',
                address: 'Blk 20 Lot 31, Artagen St., Tiera Nova Royal 2 Subd., Brgy. Bagumbong, Caloocan City',
                minister: 'Rev. Danilo Tabije',
                contact: '0921-3642647',
                worshipTime: '10:00 AM – 12:00 NN',
                elders: ['Elder Mar Ritual', 'Elder Marte Rez', 'Elder Rolando Rez', 'Elder Mark Cenicio'],
            },
            {
                name: 'One Word Covenant Presbyterian Church',
                address: '1549 Ampalaya St., Manggahan St., Napico, Manggahan, Pasig City',
                minister: 'Rev. Lowe Tepase',
                contact: '0920-6789937',
                worshipTime: '10:00 AM – 12:00 NN',
                elders: ['Elder Willy Gico', 'Elder Val Geco'],
            },
            {
                name: 'Christ Covenant Presbyterian Church',
                address: 'RF Lopez Bldg., N. Lopez Ave., San Isidro, Parañaque City',
                minister: 'Rev. Edgar Adra (Moderator)',
                contact: '0935-9955970',
                worshipTime: '1:30 PM – 3:00 PM',
                elders: ['Elder Constancio Cabatay'],
            },
            {
                name: 'Las Piñas Presbyterian Church',
                address: '862 Interior San Jose St., Brgy. Daniel Fajardo, Las Piñas City',
                minister: 'Rev. Rio Carillo',
                contact: '0999-9965713',
                worshipTime: '10:00 AM – 11:30 AM',
            },
            {
                name: 'New Life in Christ Bicutan Presbyterian Church',
                address: '#1 Pinagkaisa St., Brgy. New Lower Bicutan, Taguig City',
                minister: 'Rev. Menard Diño',
                contact: '0976-3005997',
                worshipTime: '9:30 AM – 11:30 AM',
            },
            {
                name: 'Jesus the Living Stone Presbyterian Church',
                address: 'Rajah Sumakwel St., Brgy. Upper Bicutan, Taguig City',
                minister: 'Rev. Alexander Landeza (Pulpit Supply)',
                contact: '0992-5097023',
                worshipTime: '10:30 AM – 12:00 NN',
            },
        ],
    },
    {
        id: '8',
        name: 'Cavite Presbytery',
        region: 'Luzon',
        description: 'The regional body for churches in Cavite.',
        officers: [
            { name: 'Rev. Francis Bañaga', role: 'Moderator' },
            { name: 'Rev. Charles O. Alcid', role: 'Vice Moderator' },
            { name: 'Rev. Robin M. Abaño', role: 'Recording Clerk' },
            { name: 'Rev. Generus Ignacio', role: 'Treasurer' },
        ],
        churches: [
            {
                name: 'AMW Gentri Church',
                address: 'Tinungan, Mangahan, Gen. Trias City',
                minister: 'Rev. Francis Bañaga',
                associatePastors: ['Ptr. Febhu Brian Escototo'],
                contact: '09985525765',
                worshipTime: '10:30 AM',
                elders: ['Elder Alfred Aroma', 'Elder Jimmy Teodore'],
            },
            {
                name: 'Emmanuel Christian Church',
                address: 'B1-B L59-60 P5 Tierra Nevada, San Francisco, General Trias, Cavite',
                minister: 'Rev. Laurence Gatawa',
                associatePastors: ['Pastor Albert Gono (Licentiate)', 'Pastor Arman Urbiztondo (Ministerial Candidate)'],
                worshipTime: '9:00 AM',
                elders: ['Elder Ador Dumanayos', 'Elder Carlito Mabanes', 'Elder Ric Dela Cruz'],
            },
            {
                name: 'Gospel Bearer Christian Ministry',
                address: 'Salawag Junction, Bgy. Salawag, City of Dasmariñas, Cavite',
                minister: 'Rev. Nicodemus B. Paguia',
                contact: '0968-664-1409',
                worshipTime: '10:00 AM',
                elders: ['Elder Lito Baldon', 'Elder Rolando Bacani', 'Elder Dave Paguia (On leave)'],
            },
            {
                name: 'Holy Blessing Presbyterian Church',
                address: 'Congressional Road Salitran III City of Dasmariñas',
                minister: 'Rev. Felix C. Frias Jr. & Rev. Reydentor D. Panganiban Jr.',
                associatePastors: ['Pastor Marl Jayson Gabileo'],
                contact: '09657092885',
                worshipTime: '9:30 AM',
                elders: ['Elder Roel Garde', 'Elder Antonio Cadiz'],
            },
            {
                name: 'Holy Light Mission Church',
                address: 'B18 L 9-10, Laos St. San Marino Central A, Salawag, Dasmariñas, Cavite. 4114',
                minister: 'Rev. Charles O. Alcid',
                associatePastors: ['Ptr. Victor Abraham Cacam (Licentiate)'],
                contact: '09463953455',
                worshipTime: '9:00 AM – 11:00 AM',
                elders: ['Elder Vic Pajarillo', 'Elder Edgar Tindoc'],
            },
            {
                name: 'Molino Presbyterian Church',
                address: 'Blk 2 L-15 Joshua St. Infant Jesus Subd. Molino 2 City of Bacoor',
                minister: 'Rev. Nelson M. Carillo',
                contact: '09942425370',
                worshipTime: '9:00 – 10:30 AM',
                elders: ['Elder Ricardo Panizal', 'Elder Percival Castillo', 'Elder Joselito Guilleno'],
            },
            {
                name: 'Oikos Reformed Christian Church',
                address: 'Sitio Pook, Paliparan 3, City of Dasmariñas, Cavite',
                minister: 'Rev. Gil Hiponia',
                associatePastors: ['Pastor Reuel Perez'],
                contact: '09173100796',
                worshipTime: '9:30 AM – 11:30 AM',
                elders: ['Elder Ignacio Alamano', 'Elder Domingo Artacho'],
            },
            {
                name: 'Peniel Presbyterian Church - Dasma',
                address: '9015 Crispulo Aguinaldo Street Barangay Salitran 2 City of Dasmariñas Cavite',
                minister: 'Rev. Aldrin Calaluan',
                contact: '09464374768',
                worshipTime: '9:00 AM',
                elders: ['Elder Rodrigo Dilao', 'Elder Mark Nestor Moreno'],
            },
            {
                name: 'Peniel Presbyterian Church - Pasong Kawayan',
                address: 'Blk35 L11 Biliran St General Dos Subd. Pasong Kawayan, General Trias, Cavite',
                minister: 'Rev. Ferdinand D. Domingo',
                contact: '09058977059',
                worshipTime: '8:00 AM – 10:00 AM',
                elders: ['Elder Noel Collao', 'Elder Joorvic Valmores', 'Elder Joemar Arribe'],
            },
            {
                name: 'Bagong Bayan Presbyterian Church',
                address: 'Carlos Q. Trinidad Ave., Salitran IV, City of Dasmariñas, Cavite',
                minister: 'Rev. Orlando M. Tabotabo',
                associatePastors: ['Pastor Jose Noel Lozano'],
                contact: '0977 302 9688 & 0997 172 4023',
                worshipTime: '9:00 AM – 11:00 AM',
                elders: ['Elder Adriano Loresco'],
            },
            {
                name: 'Christ Above All Church',
                address: 'Phs 1 Blk 12 Lot 6 Solar Homes Subd., San Agustin 1, Dasmariñas City, Cavite',
                minister: 'Rev. Joel G. Gallandez',
                contact: '09355163094',
                worshipTime: '9:45 AM',
            },
            {
                name: 'Crown of Glory Presbyterian Church',
                address: 'Blk 17 Lot 7-11, Heart Foundation Ph 1, Punta 1, Tanza Cavite',
                minister: 'Rev. Crisostomo Sibulo & Rev. Mark Joel Sibulo',
                associatePastors: ['Ptr. Ian Rabilas (Licentiate)'],
                contact: '09453351944 / 09957105293',
                worshipTime: '10:00 AM',
            },
            {
                name: 'Dasmariñas Presbyterian Church',
                address: 'Carlos Q. Trinidad Ave., Salitran IV, City of Dasmariñas, Cavite',
            },
            {
                name: 'Heneral Uno Presbyterian Church',
                address: 'Pasong Kawayan 2 Heneral 1',
                minister: 'Rev. Generus Ignacio & Rev. Noel Sahagun',
                contact: '09668223616',
                worshipTime: '9:00 AM – 12:00 NN',
                elders: ['Elder Alberto Santos'],
            },
            {
                name: 'Jesus My Redeemer Christian Church',
                address: 'Purok 5 Brgy. Lapidario Trece Martires City Cavite',
                minister: 'Rev. Jhun Frias & Rev. Thordz Panganiban',
                contact: '09657092885',
                worshipTime: '7:30 AM',
                elders: ['Elder Andrew Gajela'],
            },
            {
                name: 'Jesus the Only Redeemer Church',
                address: 'Blk 64 Lot 3&4 Phase 4, Elisa Homes Molino 4 Bacoor Cavite',
                minister: 'Rev. John Teodoro',
                associatePastors: ['Ptr. Karl Bryan Dela Cruz'],
                contact: '09950423088',
                worshipTime: '9:00 AM – 12:00 NN',
            },
            {
                name: 'Langkaan Christian Ministries',
                address: 'B8 L21 Mahogany St. Greenbreeze Vill. 1, Langkaan 2. Dasmariñas, Cavite',
                minister: 'Rev. Alfred Capistrano',
                contact: '09553078841',
                worshipTime: '9:30 AM',
            },
            {
                name: 'Papaya Fellowship',
                address: 'Blk 1, Lot 128, Brgy. H2, Dasmariñas City Cavite',
                minister: 'Rev. Jonathan R. Senados',
                contact: '09279559726',
                worshipTime: '10:30 AM',
                elders: ['Elder Brandon O. Saliot'],
            },
            {
                name: 'San Francisco Presbyterian Church',
                address: 'Phs 5, Blk S12a, Lot 11, Brookside Lane, San Francisco, General Trias City, Cavite',
                minister: 'Rev. Bernardo B. Santos',
                contact: '(046) 419-2805 / 0919-838-1903',
                worshipTime: '9:00 AM',
            },
            {
                name: 'Saving Grace GMA Presbyterian Church',
                address: 'Brgy Samakasite Brgy Gavino Maderan GMA Cavite',
                minister: 'Rev. Adrian B. Octaviano',
                contact: '09162953376',
                worshipTime: '9:30 AM',
                elders: ['Elder Ron Kenneth Reyes'],
            },
            {
                name: 'The Great Shepherd Christian Church',
                address: 'Blk-2 Lot-19 Minerva St., Kaunlaran Village II, Molino 3, City of Bacoor, Cavite.',
                minister: 'Rev. Elimar C. Eleazar & Rev. Aljay M. Leones',
                contact: '09777845145',
                worshipTime: '9:00 AM',
            },
            {
                name: 'Transformation Church - Tanza',
                address: 'B5, L25, Sanja Mayor Subdivision, Tanza, Cavite',
                minister: 'Rev. Francis Bañaga & Rev. Prince Samuel Santos',
                contact: '09985525765',
                worshipTime: '4:00 PM',
            },
            {
                name: 'Zion Presbyterian Church',
                address: 'Blk-173, Private Lot, Phs-4, Paliparan III, City of Dasmariñas, Cavite',
                minister: 'Rev. Robin M. Abaño',
                contact: '09064340075',
                worshipTime: '10:00 AM – 12:00 NN',
                elders: ['Elder Wilfredo Matias'],
            },
            {
                name: 'AMW Beacon Church',
                address: 'Anabu 1A, Imus City',
                minister: 'Rev. Francis Bañaga',
                associatePastors: ['Ptr. John Paul Manalo'],
                contact: '09985525765',
                worshipTime: '8:00 AM',
                elders: ['Elder Alvin Navales', 'Elder Roel Ignacio'],
            },
            {
                name: 'Burol Bethel Presbyterian Church',
                address: 'Private lot, Sarreal Compound, Brgy Burol 3 Dasmariñas City, Cavite',
                minister: 'Rev. Jay S. Gupo',
                contact: '09637154356',
                worshipTime: '10:00 AM – 12:00 NN',
            },
            {
                name: 'Jejungwon Presbyterian Church',
                address: 'Private lot (Breiz Compound) Snake Road Brgy. Salawag, Dasmariñas, Cavite',
                minister: 'Rev. Luis T. Talastas',
                associatePastors: ['Ptr. Luis Reniel (Ministerial Candidate)'],
                contact: '09464116949',
                worshipTime: '10:30 AM – 12:00 NN',
                elders: ['Elder Elden Arquisal'],
            },
            {
                name: 'Peniel Presbyterian Church - Navarro',
                address: 'Phase 5, Block 28, Lot 1 City of General Trias, Cavite',
                minister: 'Rev. Crisostomo Sibulo',
                associatePastors: ['Ptr. Christoper E. Lomio'],
                contact: '0961-641-4907',
                worshipTime: '9:00 AM',
            },
            {
                name: 'Rosario Christian Church',
                address: 'Sitio Banal, Wawa III, Rosario, Cavite',
                minister: 'Rev. Francis Bañaga',
                associatePastors: ['Ptr. Danal Aguado'],
                contact: '09985525765',
                worshipTime: '2:00 PM',
            },
            {
                name: 'Santiago Christian Fellowship',
                address: 'Santiago, General Trias, Cavite',
                minister: 'Rev. Reydentor D. Panganiban Jr. & Rev. Jhun Frias',
                contact: '09268836892',
                worshipTime: '8:30 AM',
            },
            {
                name: 'The Shepherd Presbyterian Church - Alingaro',
                address: '0201 JP Laurel St., St. Francis Subd. (Tubahan), Brgy. Alingaro, Gen. Trias City',
                minister: 'Rev. Francis Bañaga & Rev. Robert Rances',
                contact: '09985525765',
                worshipTime: '10:15 AM',
                elders: ['Elder Leo Torre'],
            },
            {
                name: 'The Shepherd Presbyterian Church - GMA',
                address: 'B4 L27 San Gabriel, GMA, Cavite',
                minister: 'Rev. Alex C. Gabriel',
                contact: '09166013829',
                worshipTime: '3:00 PM – 4:15 PM',
            },
            {
                name: 'Transformation Church - Indang',
                minister: 'Rev. Francis Bañaga',
                contact: '09985525765',
            },
            {
                name: 'Trinity Presbyterian Church',
                minister: 'Rev. Generus Ignacio & Rev. Noel Sahagun',
                contact: '09668223616',
                elders: ['Elder Alberto Santos'],
            },
        ],
    },
    { id: '9', name: 'Southern Luzon Presbytery', region: 'Luzon', officers: [], churches: [], description: 'Overseeing Presbyterian works in Southern Luzon.' },
    { id: '10', name: 'Bicol Presbytery', region: 'Luzon', officers: [], churches: [], description: 'The regional council for the Bicol region.' },
    {
        id: '11',
        name: 'Visayas Presbytery',
        region: 'Visayas',
        description: 'Serving the regional network of churches in Visayas.',
        officers: [
            { name: 'Rev. Manuel Maca', role: 'Moderator', contact: 'Danao Presbyterian Church, Olivar St. Pob. Danao City, Cebu; Contact # 0963 331 9946' },
            { name: 'Rev. Willie Q. Dindin', role: 'Vice Moderator', contact: 'Cordova Presbyterian Church, 342 Purok Kamunggay, Brgy. Alegria, Cordova; Contact #0933 480 5062' },
            { name: 'Rev. Alejandro Managbanag Jr.', role: 'Secretary', contact: 'Mandaue Presbyterian Church, Kamanggahan, Labogon, Mandaue City, Cebu; Contact: 0976-197-3902' },
            { name: 'Rev. Ramonito O. Villaver', role: 'Treasurer', contact: 'Holy Love Christian Church, San Roque, Taytay, Danao City; Contact # 0962-411-7562' },
            { name: 'Rev. Ian V. Mariano', role: 'Auditor', contact: 'Gracepointe Presbyterian Church, Brgy. Bankal, Lapu-lapu City; Contact # 0927-732-1097' },
        ],
        churches: [
            {
                name: 'Bogo Presbyterian Church',
                address: 'Upper Pandan, Bogo City, Cebu',
                minister: 'Rev. Efren Ducay Jr.',
                contact: 'Mobile: 0949-922-6869',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Bohol Shalom Presbyterian Church',
                address: 'Purok 4, Tinangnan, Tubigon, Bohol',
                minister: 'Rev. Andro Flores',
                contact: 'Mobile: 0951-207-2860',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Cagay Presbyterian Church',
                address: 'Brgy. Cagay, Sibonga, Cebu',
                minister: 'Rev. Sang Baek Kim',
                contact: 'Mobile: 0916-6911164',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Camotes Kahayag Presbyterian Church',
                address: 'Tamban, Poro Camotes, Cebu',
                minister: 'Pastor James Tachado',
                contact: 'Mobile: 0956-038-3417',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Cebu Shalom Presbyterian Church',
                address: 'A. Lopez St., V. Rama, Calamba, Cebu City',
                minister: 'Rev. Yong Woo (Abraham) Kim',
                associatePastors: ['Rev. Dennies Palma'],
                contact: 'Mobile: 0927-8758-433; 0916-3864-624; 0905-818-8441',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Cebu Shine Presbyterian Church',
                address: 'Shangrila II, Salvador Ext. Labangon, Cebu City',
                minister: 'Rev. Kwang Suk (Timothy) Choi',
                contact: 'Mobile: 0915-6780-694; 0977-7620-708',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Cogon Cruz Presbyterian Church',
                address: 'Cogon, Cruz, Danao City, Cebu',
                minister: 'Rev. Manuel Maca',
                associatePastors: ['Pastor Neale M. Maca'],
                contact: 'Mobile: 0963-331-8536',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Cordova Presbyterian Church',
                address: '342 Purok Kamunggay, Barangay. Alegria, Cordova, Cebu',
                minister: 'Rev. Willie Q. Dindin',
                contact: 'Mobile: 0933-480-5062',
                email: 'wild011908@gmail.com',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Danao Presbyterian Church',
                address: 'E. Olivar St., Poblacion, Danao City, 6004, Cebu',
                minister: 'Rev. Manuel Maca',
                associatePastors: ['Pastor Neale M. Maca'],
                contact: 'Mobile: 0963-331-9946',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Gracepointe Presbyterian Church',
                address: '2575 Sitio Mahayahay Road, Bankal, Lapu-Lapu City 6015',
                minister: 'Rev. Ian V. Mariano',
                contact: 'Mobile: 0927-732-1097',
                email: 'ianehud@yahoo.com',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Gracepointe Presbyterian Church Medellin',
                address: 'Brgy. Canhabagat Medellin Cebu',
                minister: 'Pastor Carlo Parra',
                contact: 'Mobile: 0993592723',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Kahayag Presbyterian Church',
                address: 'Consolacion, Cebu',
                minister: 'Missionary Heo, Young Hee',
                contact: 'Mobile: 0912-8201478',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Liloan Living Bread Presbyterian Church',
                address: 'Purok Upo Cogon, Catarman, Liloan, Cebu 6002',
                minister: 'Rev. Solomon Hyunin Chon',
                contact: 'Mobile: 0918-901-0763',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Mactan Samduck Church',
                address: 'Barangay Bankal Pool, Lapu-Lapu City',
                minister: 'Pastor Keventri Canoneo',
                contact: 'Mobile: 0933-092-7525',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'Mandaue Presbyterian Church',
                address: 'Sitio Kamanggahan, Labogon, Mandaue City',
                minister: 'Rev. Alejandro S. Managbanag Jr.',
                contact: 'Mobile: 0976-197-3902',
                email: 'dodong4ale@yahoo.com',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
            {
                name: 'New Light Presbyterian Church',
                address: 'Barangay Sapangdaku, Cebu City',
                minister: 'Rev. Jeson Jemol',
                contact: 'Mobile: 0935-544-1533',
                worshipTime: 'Sunday School 9:00–10:00 AM; Worship 10:00 AM–12:00 NN',
            },
        ],
    },
    { id: '12', name: 'Western Visayas Presbytery', region: 'Visayas', officers: [], churches: [], description: 'Expanding mission in Western Visayas.' },
    { id: '13', name: 'Southern Visayas Presbytery', region: 'Visayas', officers: [], churches: [], description: 'Serving Southern Visayas communities.' },
    {
        id: '14',
        name: 'Mindanao Presbytery',
        region: 'Mindanao',
        description: 'The regional body overseeing the mission in Mindanao.',
        officers: [],
        churches: [
            {
                name: 'Davao Presbyterian Church',
                address: 'Tahimik Avenue, Matina, Davao City',
                minister: 'Rev. Anacleto D. Dulong',
                associatePastors: ['Rev. Elizardo D. Hortel'],
                contact: '09459741134',
                elders: ['Elder Joel Parojinog Sr.', 'Elder Rogelio Asares'],
            },
            {
                name: 'Christian Love Church',
                address: 'Blk 21 Lot 12 Pag-Ibig Subd. Cabantian Davao City',
                minister: 'Rev. John Jay S. Farparan',
                associatePastors: ['Ptr. Roldan P. Eyo'],
                contact: '09673592392',
                elders: ['Engr. Roldan A. Sabanal'],
            },
            {
                name: 'Iligan Presbyterian Church',
                address: 'Purok 23, Zone 9, Fuentes, Maria Cristina, Iligan City',
                minister: 'Rev. Henrieto I. Pacaldo',
                contact: '(063)222-3240 / 09639540017',
            },
            {
                name: 'Surigao Presbyterian Church',
                address: 'Purok 1b, Brgy. San Juan, Surigao City',
                minister: 'Rev. Agosto H. Azarcon',
                contact: '09207534099',
            },
            {
                name: 'Butuan Presbyterian Church',
                address: 'Libertad Butuan City',
                minister: 'Rev. Noel B. Najarro',
            },
            {
                name: 'Davao Christian Church',
                address: '#8 Cabantian Rd., Buhangin, Davao City',
                minister: 'Rev. Paul Shin Ki Dae',
                associatePastors: ['Ptra. Joan Jimenez Porcadilla'],
            },
            {
                name: 'Grace Presbyterian Church',
                address: 'Pk. 17 black 13 lot 44-45 Avenue St. Green Meadows sub. Brgy. Sto. Nino Tugbok Dist. D.C.',
                minister: 'Rev. Rhyan F. Reducto',
                contact: '09063889765',
            },
            {
                name: 'Panabo Presbyterian Church',
                address: 'Prk. 6 Savalcion Panabo City',
                minister: 'Pastor Lorven Saguenza',
                contact: '0948-617-7166',
            },
            {
                name: 'Davao Saesarang Presbyterian Church',
                address: 'Sta. Marta, Catalunan Grande Talomo Davao City',
                minister: 'Rev. Rene M. Ali',
                contact: '09324847572',
            },
            {
                name: 'Abundant Church',
                address: 'SOS Drive Jeriza Subd. Brgy. Wilfredo Aquino Agdao D.C',
                minister: 'Rev. Paul Lee',
                associatePastors: ['Ptr. Analiza E. Cempron'],
                contact: '09914524856',
            },
            {
                name: 'Springwater Presbyterian Church',
                address: 'P5 Pag-Antayan Cantilan Surigao Del Sur',
                minister: 'Rev. Junghoe Her',
                contact: '0862125290',
            },
            {
                name: 'Yangmoon Community Church',
                address: 'Purok C, Barangay Bawing General Santos City.',
                minister: 'Rev. Alvie Angeles',
                contact: '09652518729',
            },
            {
                name: 'Matina Christian Church',
                address: 'Maharika Village Matina Aplaya',
                minister: 'Rev. Jongsu Kim',
                associatePastors: ['Ptr. Jabin Bago'],
                contact: '09998517110',
            },
            {
                name: 'Ligth Presbyterian Church',
                address: 'Purok 4 phase 3 Ilam Mulig Toril, Davao City',
                minister: 'Rev. Jimboy M. Bayugan',
                contact: '09368624640 / 09382457987',
            },
            {
                name: 'Hope Presbyterian Church',
                address: 'Brgy. Sto.Nino phase 2, Purok 9, Christ the King st. Tugbok district D.C',
                minister: 'Rev. Eleasar G. Diale',
                contact: '09514092204',
            },
            {
                name: 'Davao Center Church',
                address: 'KM10 Suraya Village Cabantian, Davao City',
                minister: 'Rev. Seounghwan Jang (Joseph Jang)',
                associatePastors: ['Ptr. Mark Gubat'],
            },
            {
                name: 'Deca Homes Christian Church',
                address: 'B33 L11/13 Deca Homes Subd. Cabantian Davao City',
                minister: 'Rev. Jay Ramirez Pedolin',
                contact: '09651304964 (32-12669)',
            },
            {
                name: 'Seodoo Hermon Presbyterian Church',
                address: 'Purok 51 Green Valley Maa',
                minister: 'Rev. Sammy T. Villegas',
                contact: '09396479304',
            },
            {
                name: 'Gospel Community Church',
                address: 'Upper Dampa Brgy.Magtuod Davao City',
                minister: 'Rev. Elias C. Magandam',
                contact: '09555145271',
            },
            {
                name: 'Shalom Presbyterian Church',
                address: 'Maragusan Davao De Oro',
                minister: 'Rev. Nonie Cani',
                contact: '09055809313',
            },
            {
                name: 'Overflowing Fellowship Church',
                address: 'Prk2 Km12, Catalunan Pequeño, Davao City, 8000',
                minister: 'Rev. Philip, Seongil Jeon',
                contact: '09639099260, 2375524',
            },
            {
                name: 'Immanuel Presbyterian Church',
                address: 'SM Village sardonyx st. Alzate comp. Bangkal Dvo City',
                associatePastors: ['Ptra. Perla Telloro'],
                contact: '09465650647',
            },
            {
                name: 'Tribal Christian Church',
                address: 'Sitio Ariston, Poblacion, Malungon, Sarangani Province',
                associatePastors: ['Ptra. Jovelyn E. Millan'],
                contact: '09307788502',
            },
            {
                name: 'South Hill Community Church',
                address: 'Purok 16, Grabahan Crossing Bayabas Toril Davao City',
                minister: 'Rev. David Kim',
                contact: '09292824691',
            },
            {
                name: 'Cross Road Presbyterian Church',
                address: 'Kalubihan Kampo Uno Catalunan Grande Davao City',
                minister: 'Rev. Geneboy Ceniza',
                contact: '09632637996',
            },
            {
                name: 'People Toward Christ',
                address: 'Pearl Street Gem Village Maa Davao City',
                minister: 'Rev. Dennis S. Ang',
                contact: '09165947998',
                elders: ['Elder Jayson Liwanag', 'Elder Rassel Bajenting'],
            },
            {
                name: 'Panacan Christian Church',
                address: 'Purok 24-A Veterans Village Malagamot Panacan Davao City',
                minister: 'Rev. Sung Hong, Oh',
                associatePastors: ['Pastora Faith Labiton'],
                contact: '09159101113',
            },
            {
                name: 'Langub Dream Presbyterian Church',
                address: 'Purok 3 Centro Langub Davao City',
                minister: 'Rev. Francis Villegas',
                contact: '09294817097',
            },
            {
                name: 'New Heaven Presbyterian Church',
                address: 'P2 B2 L29 Guiho St. Awhag Subd Brgy. 19-B POB, D.C',
                minister: 'Ptr. Jeffrey O. Lumba',
                contact: '0910-377-7024, 0938-152-8227, 0955-100-4355',
            },
            {
                name: 'Fruitful Presbyterian Church',
                address: 'Prk. 9 Ledesma Taluntalunan Makilala North Cotabato',
                minister: 'Rev. Argie I. Rebelala',
                associatePastors: ['Pastor Mary I. Rebelala'],
                contact: '09127047073',
            },
            {
                name: 'Living Hope Christian Church',
                address: 'Prk. 9-A Brgy. Tacunan Tugbok District Davao city',
                minister: 'Rev. Ramil S. Castro',
                contact: '09265174991',
            },
            {
                name: 'Ebenezer Presbyterian Church',
                address: 'Purok 15 Mahayahay Tugbok Proper Davao City',
                minister: 'Rev. Edgar Duarte',
                contact: '09161041804',
            },
            {
                name: 'Peniel Evangelical Church',
                address: 'Sta. Fe, Dapa, Surigao del norte',
                minister: 'Pastor Emelio Plaza Pacañor',
                contact: '09197550456',
            },
            {
                name: 'New-Life Christian Church',
                address: 'Derling Street, Pepsi Village, Dumoy, D. C',
                minister: 'Rev. Bernardo P. Figueras',
                contact: '297-1421 / 09067618663',
            },
            {
                name: 'Jesus Centered Church',
                address: 'Blk.17 26 Amarillo Pink St. Dacoville Dumoy D. C',
                minister: 'Rev. Care S. Daggon',
                contact: '09469282706',
            },
            {
                name: 'Digongan Presbyterian Church',
                address: 'Digongan kitao-Tao Bukidnon',
                minister: 'Ptr. Narciso Querpo',
                associatePastors: ['Ptr. Antonio Querpo'],
                contact: '09751058781',
                elders: ['Elder Samuel Villegas'],
            },
            {
                name: 'Mizpah Presbyterian Church',
                address: 'Mizpah Digongan Kitao-Tao Bukidnon',
                minister: 'Pastor Jan Lee Ondac',
                associatePastors: ['Ptr. Romy Mangguyod'],
                contact: '09751058781',
                elders: ['Elder Mawrisyo Banayao'],
            },
            {
                name: 'Zion Presbyterian Church',
                address: 'Purok 3 Bankas Heights Toril Davao City',
                minister: 'Rev. Richard Sumaliling',
                associatePastors: ['Ptra. Chona Sumaliling'],
                contact: '09095863756',
            },
            {
                name: 'Bangkal Presbyterian Church',
                address: 'Prk. 71, Speed Bangkal, Brgy, Talomo D.C.',
                minister: 'Ptr. Jason Faith T. Langgote',
                contact: '09512017770',
            },
            {
                name: 'Vineyard Presbyterian Church',
                address: 'Prk. 6, Bangkas Hieghts, Toril, Davao City',
                minister: 'Ptr. Ritchie C. Diaz',
                associatePastors: ['Ptra. Venus B. Diaz'],
            },
            {
                name: 'Landmark Bible Church',
                address: 'MIV Poblacion Uno Bansalan Davao del Sur',
                minister: 'Ptr. Leonardo Fernandez',
                contact: '09161298331',
            },
            {
                name: 'Lanipao Dream Presbyterian Church',
                address: 'Lanipao Pangan Kitao-tao Bukidnon',
                minister: 'Ptr. Janlee Ondac',
                associatePastors: ['Ptra. Bernadette Talabangonan'],
                contact: '09161298331',
            },
            {
                name: 'Samal Emmanuel Presbyterian Church',
                address: 'Brgy. Limao, Penaplata, Samal Devao Del Norte',
                minister: 'Ptr. Recson Saigad',
            },
            {
                name: 'First Mati Presbyterian Church',
                address: 'Purk Mapayapa, Brgy. Matiao, Mati City',
            },
        ],
    },
    {
        id: '15',
        name: 'Bulacan Presbytery',
        region: 'Luzon',
        description: 'The regional council overseeing Presbyterian churches in the province of Bulacan.',
        officers: [
            { name: "Rev. Aurelio 'Jhune' T. Joseph Jr.", role: 'Moderator' },
            { name: 'Rev. Agripino M. Kabiling', role: 'Vice-Moderator' },
            { name: 'Rev. Samuel T. Suyao', role: 'Recording Clerk' },
            { name: 'Elder Kristoffer Ian M. Marquez', role: 'Treasurer', contact: '09157824676' },
        ],
        churches: [
            {
                name: 'Catulinan Presbyterian Church',
                address: 'Catulinan, Baliuag, Bulacan',
                minister: 'Rev. Young Won Do',
                associatePastors: ['Ptr. Jerry Hernandez'],
                contact: '0927-478-0412',
                elders: ['Elder Rufino Hernandez'],
            },
            {
                name: "Christ's Compassion Fellowship Church",
                address: '388 Purok 3, Kabilang Tulay, Calumpang, Calumpit, Bulacan',
                minister: 'Rev. Jose C. Pagdanganan Jr.',
                associatePastors: ['Ptra. Lilet Paleg', 'Ptra. Jenina Rueda'],
                contact: '09772741587',
                email: 'josepagdanganan29@gmail.com',
                elders: ['Elder Antonio Somayang', 'Elder Mario Salonga', 'Elder Aldrin Follosco'],
            },
            {
                name: "Christ's Compassion Fellowship Church – NV 9",
                address: "North Ville 9, Brgy. Iba O'Este, Calumpit, Bulacan",
                minister: 'Ptra. Jenina Rueda',
                associatePastors: ['Sis. Noemi Nepomuceno'],
                contact: '09959351031 / 09289551158',
                email: 'ruedajenina1967@gmail.com',
                elders: ['Elder Antonio Somayang'],
            },
            {
                name: 'Church of the Lord – Longos',
                address: '698 McArthur Hi-way, Longos, City of Malolos, Bulacan',
                minister: 'Rev. Aurelio T. Joseph Jr.',
                associatePastors: ['Ptra. Lorina Flores', 'Ptr. Daniel Soriano'],
                contact: '09177596410 / 09936807837',
                email: 'cotlptrjhune@gmail.com',
                worshipTime: '8:30 AM – 10:30 AM (4:00 PM – 6:30 PM every First Sunday)',
                elders: ['Elder Adriano M. Josef', 'Elder Edgardo S. Pagdanganan'],
            },
            {
                name: 'Church of the Lord – Anilao',
                address: 'Batasan St., Anilao, City of Malolos, Bulacan',
                minister: 'Ptr. Juanito Tenorio',
                associatePastors: ['Ptr. Jestoni Reyes', 'Ptra. Manelyn C. Reyes'],
                contact: '09915323274',
            },
            {
                name: 'Immanuel Presbyterian Church',
                address: '499 Magsaysay St., Zone 3, Tangos, City of Baliwag, Bulacan',
                minister: 'Ptr. Sharlou B. Talaoc',
                contact: '0928-730-3191',
                email: 'bongtalaoc76@yahoo.com',
                elders: ['Elder Elpidio S. Gamayot'],
            },
            {
                name: 'Jesus Shepherd of Our Soul Church',
                address: 'Block 1 Lot 14 & 15, Humel Heritage Homes, Longos, City of Malolos, Bulacan',
                minister: 'Rev. Agripino M. Kabiling',
                associatePastors: ['Ptra. Zenaida Navea', 'Ptra. Maria Fe Reoyan', 'Ptra. Evelyn Kabiling'],
                contact: '09326588327 / 09458601435',
                email: 'agripinokabiling@yahoo.com.ph',
                worshipTime: '9:00 AM – 11:30 AM',
                elders: ['Elder Teodorico Navea', 'Elder Joey Ganelo'],
            },
            {
                name: 'Living Stone Presbyterian Church',
                address: '0358 Masunurin St., Fernando Subd., Bagong Nayon, Baliuag, Bulacan',
                minister: 'Rev. Samuel T. Suyao',
                contact: '0997-905-7849',
                email: 'samuelsuyao1208@gmail.com',
                worshipTime: '9:00 AM – 11:30 AM',
                elders: ['Elder Frietcher Tuazon', 'Elder Kristoffer Ian Marquez', 'Elder Rholan Nueva'],
            },
            {
                name: 'Sharon Presbyterian Church',
                address: 'Gulod, Pantubig, San Rafael, Bulacan',
                minister: 'Ptra. Helen C. Talaoc',
                associatePastors: ['Ms. Janice B. Talaoc'],
                contact: '09434393991 / 09326463942',
            },
            {
                name: 'Tilapayong Presbyterian Church',
                address: 'Daang Ramon, Magsaysay St., Tilapayong, Baliuag, Bulacan, 3006',
                minister: 'Rev. Armando T. Joseph',
                associatePastors: ['Ptra. Precy Joseph'],
                contact: '09924167449',
                email: 'armanjosep63@gmail.com',
                elders: ['Elder Fersian Toribio'],
            },
        ],
    },
];

// Seminaries / theological schools. Admin-managed via the `seminaries`
// settings key; this is the seed/fallback (mirrors defaultPresbyteries).
export const defaultSeminaries = [
    {
        id: 'ptscas',
        name: 'PTS College and Advanced Studies',
        shortName: 'PTSCAS',
        tagline: 'The national ministerial training institution of GAPCP',
        type: 'college',
        about:
            'PTS College and Advanced Studies (PTSCAS) is the national institution of the General Assembly of the Presbyterian Church of the Philippines (GAPCP). It serves as the main ministerial training school of the denomination, rooted in the Reformed tradition. PTSCAS offers quality Christian education from basic to advanced levels.',
        location: '',
        website: 'https://ptscas.edu.ph',
        contact: '',
        vision:
            "To be a leading Reformed Christian institution that proclaims the Gospel, ministers to the church, society, and God's creation.",
        mission: [
            'Provide quality and holistic Christian education',
            'Train men and women for church-building and societal transformation',
            "Serve as a catalyst for the expansion of God's kingdom",
        ],
        statementOfFaith: [],
        officers: [],
        faculty: [],
        programs: [
            { name: 'K–12 Program', duration: '', units: '', description: 'Elementary, Junior High, and Senior High School', highlights: [] },
            { name: "Bachelor's Degree Programs", duration: '', units: '', description: 'Theology, Christian Education, and related fields', highlights: [] },
            { name: "Master's / Seminary Degrees", duration: '', units: '', description: 'Master of Divinity, Master of Arts in various ministries', highlights: [] },
            { name: 'Doctoral Degree Programs', duration: '', units: '', description: 'Doctor of Ministry and Ph.D. programs', highlights: [] },
        ],
        admissions: { whoMayApply: [], requirements: [] },
        schedule: { day: '', time: '', mode: '', load: '' },
        photoUrl: '',
    },
    {
        id: 'pbsi-bulacan',
        name: 'Presbyterian Bible Seminary Inc. – Bulacan Annex',
        shortName: 'PBSI – Bulacan Annex',
        tagline: 'Reformed and Christ-centered theological education',
        type: 'seminary',
        about:
            'Presbyterian Bible Seminary Inc. – Bulacan Annex is the officially recognized regional extension of Presbyterian Bible Seminary Inc. (PBSI), with its main campus located in Angeles City, Pampanga. As a duly registered non-stock, non-profit educational institution under SEC Registration No. 2024010129878-00, PBSI is committed to providing Reformed and Christ-centered theological education to individuals who are called to serve the Church and participate in the advancement of God’s kingdom. The seminary seeks to equip future pastors, missionaries, church leaders, and Christian workers through sound biblical instruction, spiritual formation, and practical ministry training. PBSI – Bulacan Annex welcomes students from all Christian denominations and is not exclusive to Presbyterian members.',
        location:
            'Jesus Shepherd of Our Soul (JSOOS), Blk. 1, Lot 14 & 15, Humel Heritage Homes, Longos, City of Malolos, Bulacan',
        website: '',
        contact: '',
        vision:
            "To be a leading Reformed Christian institution in Central Luzon and Bulacan that faithfully proclaims the Gospel and ministers to the Church, society, and God’s creation.",
        mission: [
            'Provide quality and holistic Christian educational services.',
            'Train men and women for the edification of the Church and the transformation of society.',
            "Serve as a catalyst for the expansion of God’s kingdom on earth.",
        ],
        statementOfFaith: [
            { title: 'Sola Scriptura', subtitle: 'Scripture Alone' },
            { title: 'Sola Fide', subtitle: 'Faith Alone' },
            { title: 'Sola Gratia', subtitle: 'Grace Alone' },
            { title: 'Solus Christus', subtitle: 'Christ Alone' },
            { title: 'Soli Deo Gloria', subtitle: 'Glory to God Alone' },
        ],
        officers: [
            { name: 'Rev. Joval Kinisamal', role: 'President (PBSI Main Campus)' },
            { name: 'Rev. Jhune Josep', role: 'School Administrator' },
            { name: 'Rev. Samuel Suyao', role: 'Dean of Academic & Student Affairs' },
            { name: 'Ptra. Helen Talaoc', role: 'School Registrar' },
            { name: 'Ptra. Zenaida Navea', role: 'Accounting & Finance' },
            { name: 'Ptra. Lhorie Flores', role: 'School Secretary' },
        ],
        faculty: [
            'Rev. Jose Pagdanganan',
            'Rev. Agripino Kabiling',
            'Rev. Arman Josep',
            'Ptra. Lhorie Flores',
            'Ptra. Zenaida Navea',
        ],
        programs: [
            {
                name: 'Bachelor of Theology (B.Th.)',
                duration: 'Three (3) years',
                units: '122 units',
                description:
                    'A comprehensive three-year degree program designed to prepare students for pastoral ministry, church leadership, missions, and Christian education. Graduation requires completion of all 122 required units.',
                highlights: [
                    'Trimester-based academic calendar',
                    'Strong emphasis on biblical instruction and hands-on ministry',
                    'Field Ministry training in actual church settings',
                    'Minimum of 18 units per trimester',
                ],
            },
            {
                name: 'Bachelor of Christian Ministry (BCM)',
                duration: '1 Year',
                units: '60 units',
                description:
                    'Foundational theological and ministry training. Field Ministry subjects are primarily for reporting purposes; students submit prescribed ministry engagement forms weekly. Units may later be credited toward the B.Th. degree.',
                highlights: [],
            },
            {
                name: 'Diploma in Theological Studies (DTS)',
                duration: '',
                units: '24 units',
                description:
                    "For individuals who already possess a four-year bachelor’s degree and desire formal theological education. Subjects marked with an asterisk (*) are prerequisite courses. Units may later be credited toward the B.Th. degree.",
                highlights: [],
            },
            {
                name: 'Lay Leadership Training Program',
                duration: '',
                units: '18 units',
                description:
                    "Designed for church workers and lay leaders as an introductory theological training course; may later be credited toward a bachelor’s degree program.",
                highlights: [],
            },
        ],
        admissions: {
            whoMayApply: [
                'Aspiring pastors',
                'Missionaries',
                'Church workers',
                'Christian educators',
                'Committed laypeople desiring theological training',
            ],
            requirements: [
                'Transcript of Records or Report Card',
                'PSA Birth Certificate',
                'Certificate of Good Moral Character',
                'Church Recommendation',
                'Two (2) pieces 2x2 ID pictures',
                'Personal Testimony or Essay',
                'Interview with School Leadership',
            ],
        },
        schedule: {
            day: 'Every Monday',
            time: '8:00 AM – 5:00 PM',
            mode: 'Primarily face-to-face, with blended or online options depending on instructor availability',
            load: 'Six (6) subjects per trimester (18 units); 1 hour and 30 minutes per subject',
        },
        photoUrl: '',
    },
];
