// Static reference data used by the UI. Admin-managed content lives in Firestore;
// these are not seeded into the database — they are fallbacks/option lists only.

export const regions = ['NCR', 'CAR', 'Visayas', 'Mindanao', 'Luzon'];

// Presbytery shape:
// {
//   id, name, region, description, seat?, website?,
//   officers: [{ name, role, contact?, email?, photo? }],
//   churches: [{ name, address, minister, associatePastors?, contact?, email?, worshipTime?, elders?: [name] }]
// }
export const defaultPresbyteries = [
    { id: '1', name: 'Northern Luzon Presbytery', region: 'Luzon', officers: [], churches: [], description: 'Regional council overseeing Presbyterian churches in Northern Luzon.' },
    { id: '2', name: 'Central Luzon North Presbytery', region: 'Luzon', officers: [], churches: [], description: 'Serving the Northern parts of Central Luzon.' },
    { id: '3', name: 'Central Luzon Presbytery', region: 'Luzon', officers: [], churches: [], description: 'The main regional council for Central Luzon.' },
    { id: '4', name: 'Western Luzon Presbytery', region: 'Luzon', officers: [], churches: [], description: 'Overseeing churches across Western Luzon.' },
    {
        id: '5',
        name: 'NCR Presbytery - North Metro',
        region: 'NCR',
        officers: [],
        churches: [],
        description: 'Serving churches in the Northern Metro Manila area.',
    },
    { id: '6', name: 'Rizal Presbytery', region: 'Luzon', officers: [], churches: [], description: 'Serving the province of Rizal and surrounding areas.' },
    {
        id: '7',
        name: 'NCR Presbytery - South Metro',
        region: 'NCR',
        description: 'Serving churches in the Southern Metro Manila area.',
        officers: [
            { name: 'Rev. Rodrigo Figueroa', role: 'Moderator' },
            { name: 'Rev. Danilo Tabije', role: 'Vice-Moderator' },
            { name: 'Rev. Menard Diño', role: 'Recording Clerk' },
            { name: 'Elder Leonardo Canto', role: 'Treasurer' },
            { name: "Elder Constancio 'Natan' Cabatay", role: 'Auditor' },
        ],
        churches: [
            {
                name: 'Gospel Mission Presbyterian Church',
                address: '#42 F. Banaag Street, Brgy. Pineda, Pasig City',
                minister: 'Rev. Angelito Carillo',
                contact: '0908-7239093',
                worshipTime: '10:00 AM – 12:00 NN',
                elders: ['Elder Lyndon Calbone', 'Elder Francis Verches', 'Elder Jaime Mahinay'],
            },
            {
                name: 'Ichthus Presbyterian Church',
                address: 'L4 B7, Banner Ave, St. Martin Village, 4th Estate Subd., Brgy. San Antonio, Sucat, Parañaque City',
                minister: 'Rev. Edgar Adra',
                contact: '0935-9955970',
                worshipTime: '10:00 AM – 11:30 AM',
                elders: ['Elder Ferdinand Lorenzana', "Elder Ernesto 'Jhun' Garcia", 'Elder Alexander Co', 'Elder Leonardo Canto'],
            },
            {
                name: 'Grace Community Presbyterian Church',
                address: 'Blk 12 Lot 43 America St., Corner Australia, EP Housing Village, Brgy. Pinagsama Phase 2, Taguig City',
                minister: 'Rev. Rodrigo Figueroa',
                contact: '0945-1196953',
                worshipTime: '10:00 AM – 11:30 AM',
                elders: ['Elder Joel Balabbo', 'Elder Nelson Rodriguez'],
            },
            {
                name: 'Bread for the Word Presbyterian Church',
                address: 'Blk 20 Lot 31, Artagen St., Tiera Nova Royal 2 Subd., Brgy. Bagumbong, Caloocan City',
                minister: 'Rev. Danilo Tabije',
                contact: '0921-3642647',
                worshipTime: '10:00 AM – 12:00 NN',
                elders: ['Elder Mar Ritual', 'Elder Marte Rez', 'Elder Rolando Rez', 'Elder Mark Cenicio'],
            },
            {
                name: 'One Word Covenant Presbyterian Church',
                address: '1549 Ampalaya St., Manggahan St., Napico, Manggahan, Pasig City',
                minister: 'Rev. Lowe Tepase',
                contact: '0920-6789937',
                worshipTime: '10:00 AM – 12:00 NN',
                elders: ['Elder Willy Gico', 'Elder Val Geco'],
            },
            {
                name: 'Christ Covenant Presbyterian Church',
                address: 'RF Lopez Bldg., N. Lopez Ave., San Isidro, Parañaque City',
                minister: 'Rev. Edgar Adra (Moderator)',
                contact: '0935-9955970',
                worshipTime: '1:30 PM – 3:00 PM',
                elders: ['Elder Constancio Cabatay'],
            },
            {
                name: 'Las Piñas Presbyterian Church',
                address: '862 Interior San Jose St., Brgy. Daniel Fajardo, Las Piñas City',
                minister: 'Rev. Rio Carillo',
                contact: '0999-9965713',
                worshipTime: '10:00 AM – 11:30 AM',
                elders: [],
            },
            {
                name: 'New Life in Christ Bicutan Presbyterian Church',
                address: '#1 Pinagkaisa St., Brgy. New Lower Bicutan, Taguig City',
                minister: 'Rev. Menard Diño',
                contact: '0976-3005997',
                worshipTime: '9:30 AM – 11:30 AM',
                elders: [],
            },
            {
                name: 'Jesus the Living Stone Presbyterian Church',
                address: 'Rajah Sumakwel St., Brgy. Upper Bicutan, Taguig City',
                minister: 'Rev. Alexander Landeza (Pulpit Supply)',
                contact: '0992-5097023',
                worshipTime: '10:30 AM – 12:00 NN',
                elders: [],
            },
        ],
    },
    { id: '8', name: 'Cavite Presbytery', region: 'Luzon', officers: [], churches: [], description: 'The regional body for churches in Cavite.' },
    { id: '9', name: 'Southern Luzon Presbytery', region: 'Luzon', officers: [], churches: [], description: 'Overseeing Presbyterian works in Southern Luzon.' },
    { id: '10', name: 'Bicol Presbytery', region: 'Luzon', officers: [], churches: [], description: 'The regional council for the Bicol region.' },
    { id: '11', name: 'Visayas Presbytery', region: 'Visayas', officers: [], churches: [], description: 'Serving the regional network of churches in Visayas.' },
    { id: '12', name: 'Western Visayas Presbytery', region: 'Visayas', officers: [], churches: [], description: 'Expanding mission in Western Visayas.' },
    { id: '13', name: 'Southern Visayas Presbytery', region: 'Visayas', officers: [], churches: [], description: 'Serving Southern Visayas communities.' },
    { id: '14', name: 'Mindanao Presbytery', region: 'Mindanao', officers: [], churches: [], description: 'The regional body overseeing the mission in Mindanao.' },
    {
        id: '15',
        name: 'Bulacan Presbytery',
        region: 'Luzon',
        description: 'The regional council overseeing Presbyterian churches in the province of Bulacan.',
        officers: [
            { name: "Rev. Aurelio 'Jhune' T. Joseph Jr.", role: 'Moderator' },
            { name: 'Rev. Agripino M. Kabiling', role: 'Vice-Moderator' },
            { name: 'Rev. Samuel T. Suyao', role: 'Recording Clerk' },
            { name: 'Elder Kristoffer Ian M. Marquez', role: 'Treasurer', contact: '09157824676' },
        ],
        churches: [
            {
                name: 'Catulinan Presbyterian Church',
                address: 'Catulinan, Baliuag, Bulacan',
                minister: 'Rev. Young Won Do',
                associatePastors: ['Ptr. Jerry Hernandez'],
                contact: '0927-478-0412',
                elders: ['Elder Rufino Hernandez'],
            },
            {
                name: "Christ's Compassion Fellowship Church",
                address: '388 Purok 3, Kabilang Tulay, Calumpang, Calumpit, Bulacan',
                minister: 'Rev. Jose C. Pagdanganan Jr.',
                associatePastors: ['Ptra. Lilet Paleg', 'Ptra. Jenina Rueda'],
                contact: '09772741587',
                email: 'josepagdanganan29@gmail.com',
                elders: ['Elder Antonio Somayang', 'Elder Mario Salonga', 'Elder Aldrin Follosco'],
            },
            {
                name: "Christ's Compassion Fellowship Church – NV 9",
                address: "North Ville 9, Brgy. Iba O'Este, Calumpit, Bulacan",
                minister: 'Ptra. Jenina Rueda',
                associatePastors: ['Sis. Noemi Nepomuceno'],
                contact: '09959351031 / 09289551158',
                email: 'ruedajenina1967@gmail.com',
                elders: ['Elder Antonio Somayang'],
            },
            {
                name: 'Church of the Lord – Longos',
                address: '698 McArthur Hi-way, Longos, City of Malolos, Bulacan',
                minister: 'Rev. Aurelio T. Joseph Jr.',
                associatePastors: ['Ptra. Lorina Flores', 'Ptr. Daniel Soriano'],
                contact: '09177596410 / 09936807837',
                email: 'cotlptrjhune@gmail.com',
                worshipTime: '8:30 AM – 10:30 AM (4:00 PM – 6:30 PM every First Sunday)',
                elders: ['Elder Adriano M. Josef', 'Elder Edgardo S. Pagdanganan'],
            },
            {
                name: 'Church of the Lord – Anilao',
                address: 'Batasan St., Anilao, City of Malolos, Bulacan',
                minister: 'Ptr. Juanito Tenorio',
                associatePastors: ['Ptr. Jestoni Reyes', 'Ptra. Manelyn C. Reyes'],
                contact: '09915323274',
                elders: [],
            },
            {
                name: 'Immanuel Presbyterian Church',
                address: '499 Magsaysay St., Zone 3, Tangos, City of Baliwag, Bulacan',
                minister: 'Ptr. Sharlou B. Talaoc',
                contact: '0928-730-3191',
                email: 'bongtalaoc76@yahoo.com',
                elders: ['Elder Elpidio S. Gamayot'],
            },
            {
                name: 'Jesus Shepherd of Our Soul Church',
                address: 'Block 1 Lot 14 & 15, Humel Heritage Homes, Longos, City of Malolos, Bulacan',
                minister: 'Rev. Agripino M. Kabiling',
                associatePastors: ['Ptra. Zenaida Navea', 'Ptra. Maria Fe Reoyan', 'Ptra. Evelyn Kabiling'],
                contact: '09326588327 / 09458601435',
                email: 'agripinokabiling@yahoo.com.ph',
                worshipTime: '9:00 AM – 11:30 AM',
                elders: ['Elder Teodorico Navea', 'Elder Joey Ganelo'],
            },
            {
                name: 'Living Stone Presbyterian Church',
                address: '0358 Masunurin St., Fernando Subd., Bagong Nayon, Baliuag, Bulacan',
                minister: 'Rev. Samuel T. Suyao',
                contact: '0997-905-7849',
                email: 'samuelsuyao1208@gmail.com',
                worshipTime: '9:00 AM – 11:30 AM',
                elders: ['Elder Frietcher Tuazon', 'Elder Kristoffer Ian Marquez', 'Elder Rholan Nueva'],
            },
            {
                name: 'Sharon Presbyterian Church',
                address: 'Gulod, Pantubig, San Rafael, Bulacan',
                minister: 'Ptra. Helen C. Talaoc',
                associatePastors: ['Ms. Janice B. Talaoc'],
                contact: '09434393991 / 09326463942',
                elders: [],
            },
            {
                name: 'Tilapayong Presbyterian Church',
                address: 'Daang Ramon, Magsaysay St., Tilapayong, Baliuag, Bulacan, 3006',
                minister: 'Rev. Armando T. Joseph',
                associatePastors: ['Ptra. Precy Joseph'],
                contact: '09924167449',
                email: 'armanjosep63@gmail.com',
                elders: ['Elder Fersian Toribio'],
            },
        ],
    },
];

// Seminaries / theological schools. Admin-managed via the `seminaries`
// settings key; this is the seed/fallback (mirrors defaultPresbyteries).
export const defaultSeminaries = [
    {
        id: 'ptscas',
        name: 'PTS College and Advanced Studies',
        shortName: 'PTSCAS',
        tagline: 'The national ministerial training institution of GAPCP',
        type: 'college',
        about:
            'PTS College and Advanced Studies (PTSCAS) is the national institution of the General Assembly of the Presbyterian Church of the Philippines (GAPCP). It serves as the main ministerial training school of the denomination, rooted in the Reformed tradition. PTSCAS offers quality Christian education from basic to advanced levels.',
        location: '',
        website: 'https://ptscas.edu.ph',
        contact: '',
        vision:
            "To be a leading Reformed Christian institution that proclaims the Gospel, ministers to the church, society, and God's creation.",
        mission: [
            'Provide quality and holistic Christian education',
            'Train men and women for church-building and societal transformation',
            "Serve as a catalyst for the expansion of God's kingdom",
        ],
        statementOfFaith: [],
        officers: [],
        faculty: [],
        programs: [
            { name: 'K–12 Program', duration: '', units: '', description: 'Elementary, Junior High, and Senior High School', highlights: [] },
            { name: "Bachelor's Degree Programs", duration: '', units: '', description: 'Theology, Christian Education, and related fields', highlights: [] },
            { name: "Master's / Seminary Degrees", duration: '', units: '', description: 'Master of Divinity, Master of Arts in various ministries', highlights: [] },
            { name: 'Doctoral Degree Programs', duration: '', units: '', description: 'Doctor of Ministry and Ph.D. programs', highlights: [] },
        ],
        admissions: { whoMayApply: [], requirements: [] },
        schedule: { day: '', time: '', mode: '', load: '' },
        photoUrl: '',
    },
    {
        id: 'pbsi-bulacan',
        name: 'Presbyterian Bible Seminary Inc. – Bulacan Annex',
        shortName: 'PBSI – Bulacan Annex',
        tagline: 'Reformed and Christ-centered theological education',
        type: 'seminary',
        about:
            'Presbyterian Bible Seminary Inc. – Bulacan Annex is the officially recognized regional extension of Presbyterian Bible Seminary Inc. (PBSI), with its main campus located in Angeles City, Pampanga. As a duly registered non-stock, non-profit educational institution under SEC Registration No. 2024010129878-00, PBSI is committed to providing Reformed and Christ-centered theological education to individuals who are called to serve the Church and participate in the advancement of God’s kingdom. The seminary seeks to equip future pastors, missionaries, church leaders, and Christian workers through sound biblical instruction, spiritual formation, and practical ministry training. PBSI – Bulacan Annex welcomes students from all Christian denominations and is not exclusive to Presbyterian members.',
        location:
            'Jesus Shepherd of Our Soul (JSOOS), Blk. 1, Lot 14 & 15, Humel Heritage Homes, Longos, City of Malolos, Bulacan',
        website: '',
        contact: '',
        vision:
            "To be a leading Reformed Christian institution in Central Luzon and Bulacan that faithfully proclaims the Gospel and ministers to the Church, society, and God’s creation.",
        mission: [
            'Provide quality and holistic Christian educational services.',
            'Train men and women for the edification of the Church and the transformation of society.',
            "Serve as a catalyst for the expansion of God’s kingdom on earth.",
        ],
        statementOfFaith: [
            { title: 'Sola Scriptura', subtitle: 'Scripture Alone' },
            { title: 'Sola Fide', subtitle: 'Faith Alone' },
            { title: 'Sola Gratia', subtitle: 'Grace Alone' },
            { title: 'Solus Christus', subtitle: 'Christ Alone' },
            { title: 'Soli Deo Gloria', subtitle: 'Glory to God Alone' },
        ],
        officers: [
            { name: 'Rev. Joval Kinisamal', role: 'President (PBSI Main Campus)' },
            { name: 'Rev. Jhune Josep', role: 'School Administrator' },
            { name: 'Rev. Samuel Suyao', role: 'Dean of Academic & Student Affairs' },
            { name: 'Ptra. Helen Talaoc', role: 'School Registrar' },
            { name: 'Ptra. Zenaida Navea', role: 'Accounting & Finance' },
            { name: 'Ptra. Lhorie Flores', role: 'School Secretary' },
        ],
        faculty: [
            'Rev. Jose Pagdanganan',
            'Rev. Agripino Kabiling',
            'Rev. Arman Josep',
            'Ptra. Lhorie Flores',
            'Ptra. Zenaida Navea',
        ],
        programs: [
            {
                name: 'Bachelor of Theology (B.Th.)',
                duration: 'Three (3) years',
                units: '122 units',
                description:
                    'A comprehensive three-year degree program designed to prepare students for pastoral ministry, church leadership, missions, and Christian education. Graduation requires completion of all 122 required units.',
                highlights: [
                    'Trimester-based academic calendar',
                    'Strong emphasis on biblical instruction and hands-on ministry',
                    'Field Ministry training in actual church settings',
                    'Minimum of 18 units per trimester',
                ],
            },
            {
                name: 'Bachelor of Christian Ministry (BCM)',
                duration: '1 Year',
                units: '60 units',
                description:
                    'Foundational theological and ministry training. Field Ministry subjects are primarily for reporting purposes; students submit prescribed ministry engagement forms weekly. Units may later be credited toward the B.Th. degree.',
                highlights: [],
            },
            {
                name: 'Diploma in Theological Studies (DTS)',
                duration: '',
                units: '24 units',
                description:
                    "For individuals who already possess a four-year bachelor’s degree and desire formal theological education. Subjects marked with an asterisk (*) are prerequisite courses. Units may later be credited toward the B.Th. degree.",
                highlights: [],
            },
            {
                name: 'Lay Leadership Training Program',
                duration: '',
                units: '18 units',
                description:
                    "Designed for church workers and lay leaders as an introductory theological training course; may later be credited toward a bachelor’s degree program.",
                highlights: [],
            },
        ],
        admissions: {
            whoMayApply: [
                'Aspiring pastors',
                'Missionaries',
                'Church workers',
                'Christian educators',
                'Committed laypeople desiring theological training',
            ],
            requirements: [
                'Transcript of Records or Report Card',
                'PSA Birth Certificate',
                'Certificate of Good Moral Character',
                'Church Recommendation',
                'Two (2) pieces 2x2 ID pictures',
                'Personal Testimony or Essay',
                'Interview with School Leadership',
            ],
        },
        schedule: {
            day: 'Every Monday',
            time: '8:00 AM – 5:00 PM',
            mode: 'Primarily face-to-face, with blended or online options depending on instructor availability',
            load: 'Six (6) subjects per trimester (18 units); 1 hour and 30 minutes per subject',
        },
        photoUrl: '',
    },
];
